### PR TITLE
Ported Hough transform code into libattpc

### PR DESCRIPTION
**Pull request by jbradt**
First of all, sorry for the enormous pull request. There's quite a lot here to look through.

I've finished (at least for now) porting my Hough transform code to the platform-independent library. I created 5 new classes:

- `HoughTransform`, an abstract base class that does the transform itself.
- `LinearHoughTransform` and `CircularHoughTransform`, which implement the two versions. These derive from `HoughTransform`.
- `HoughSpace`, which holds the result of the transform and does conversions between radius/angle coordinates in the Hough space and bin indices.
- `HoughSpiralCleaner`, which implements the actual cleaning process through the `processEvent` method (although each step is also a separate method, so they could be done individually too. This made testing easier.)

There are also a few miscellaneous classes for holding configuration and results.

Finally, I wrote unit tests for a good amount of the code, and these can be found in the `test` directory. They can be compiled using `make test_attpc_cleaning` and then run from the command line. I used the [Catch](http://catch-lib.net/) library for unit testing since it's very simple and consists of only one header file (which is stored in `libs/catch`). You can read through the tests if you'd like and see if they seem thorough enough. There's a basic tutorial on how the testing library works [here](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md).

Please comment on this pull request if you see anything that you think should be done differently, or if you have any suggestions.

### CODE REVIEW

**Comment by Yassid** [comment]
1. - A brief tutorial explaining how to compile and run the program, if possible with an available set of test data (I think that you have some samples on the test folder), and how visualize results.

2.- Is this library adapted for the 46Ar+p case or is it a general purpose calculation? (i.e. can we find more than maximum in the accumulator space?

**Comment by jbradt** [comment]
@Yassid I just added build instructions to the README. I think that this will not be built separately from the full `libattpc` library in the future, but it can be for now, at least.

Right now, there's not really a way to _run_ the code, per se. This is a library to be used by analysis frameworks like Python or ROOT, so there's no frontend. That interface would be provided by something like ATTPCROOT or my Python framework. (At least, I think that's what the plan is.) 

That being said, the unit tests (in the `test` directory) automatically check many aspects of the code. These tests generate their own data, so I haven't used any external events. I could do that, though, if you think it would be useful.

Finally, regarding your last point, the code is not specialized to the 46Ar case specifically, but it is limited to analyzing one curved track. I don't see why it couldn't be made more general, though. I can start looking into that after this pull request gets merged.

**Comment by Yassid** [comment]
I think that having a frontend (in any of the languages/frameworks you mention) is useful for future users or developers. Whether the framework is divided in different libraries or built as a single one does not really matter as far as one can retrieve the relevant class. I think that the unit test are great, and and extension to real data would be desirable (at least this is what I would expect when planning/debugging/analyzing data during an after the experiment.

The last point is someone connected: If the library has the capability to analyzing one track (which is general enough), we will need some data preprocess to classify those tracks, such as the new framework that was developed during these last weeks. So a test bench could be a simple stand-alone program (or front end) that classifies the tracks and analyze them, using experimental data.

Of course these are just suggestions and I tend to prioritize efficiency.

I

**Comment by jbradt** [comment]
@Yassid Ok, thanks for your feedback. I think I will try adding a test case that analyzes real data, then. Regarding frontends, I am working on the Python bindings right now, and they should be ready soon. I don't know the plans for ATTPCROOT, but I think that will happen eventually too.

@ATTPC/libattpc-devs I'm going to go ahead and merge this code into `develop` since I want to start working on other things, but if you have any comments about it, please let me know and I'll be happy to address them.

**Pull request merged**
